name: Test AI Triage

on:
  workflow_dispatch:

jobs:
  triage-test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run AI Triage Action
        uses: ./.github/actions/triage-upload

        with:
          failure_file: failures/fail1.json
          triage_url: http://host.docker.internal:8000