name: AI Auto Triage Test

on:
  workflow_dispatch:

jobs:

  triage-job:

    runs-on: self-hosted

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload Failure Artifact To Triage Service
        uses: ./.github/actions/triage-upload

        with:
          failure_file: failures/fail1.json
          triage_url: http://127.0.0.1:8000